/** Public synthetic content shared by the offline demo and protocol fixtures. */
export const DEMO_ARTIFACT_REPLY = [
  'Here are three synthetic deliverables for the mobile workspace. Open each artifact to inspect it. No host files were created.',
  '',
  '```markdown filename="mobile-workspace.md"',
  '# A calmer mobile workspace',
  '',
  '## What changed',
  '- Keep the conversation and the current task together.',
  '- Show whether work is running on the server.',
  '- Open generated files in an artifact preview.',
  '',
  '| Check | Result |',
  '| --- | --- |',
  '| Keyboard spacing | Ready for device review |',
  '| Reconnect | Restore the server snapshot |',
  '| Resend | Always an explicit action |',
  '',
  '> This is a synthetic example, not a report from your host.',
  '```',
  '',
  '```html filename="workspace-card.html"',
  '<!doctype html>',
  '<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>',
  'body{font:16px system-ui;margin:0;padding:24px;background:#eef3ef;color:#20392e}article{max-width:480px;margin:auto;background:white;padding:24px;border-radius:20px}button{border:0;border-radius:12px;padding:12px 16px;background:#235f48;color:white;font:inherit}.tag{font-size:12px;letter-spacing:.08em;color:#557465}h1{font-size:30px}p{line-height:1.6}',
  '</style></head><body><article><div class="tag">PERCH · SYNTHETIC PREVIEW</div><h1>A little more room to think.</h1><p>Your agent works on the server. Your phone keeps the next decision close.</p><button id="toggle">Show the next step</button><p id="step" hidden>Review the generated file, then choose what to do next.</p></article><script>',
  'document.getElementById("toggle").onclick=()=>{const step=document.getElementById("step");step.hidden=!step.hidden};',
  '</script></body></html>',
  '```',
  '',
  '```typescript filename="connection-label.ts"',
  'type Connection = "connected" | "reconnecting" | "offline";',
  '',
  'export function connectionLabel(state: Connection): string {',
  '  const labels = {',
  '    connected: "Your server is connected",',
  '    reconnecting: "Catching up with your server",',
  '    offline: "Offline — your server may still be working",',
  '  };',
  '  return labels[state];',
  '}',
  '```',
].join('\n');
